Fix for password leak in logs
liquibase/node-liquibase pull request #100
Opened 2024-05-22 06:10 UTC by vinaypotluri

Fixes: #99

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2024-06-19 07:36 UTC, vinaypotluri commented
@filipelautert
@MalloD12
@jandroav

Would appreciate your review on this fix

2024-06-19 08:46 UTC, jandroav approved these changes

2024-06-19 16:11 UTC, filipelautert requested changes
Thanks for the PR @vinaypotluri ! Could you fix the warnings so it builds and we can get it merged?

2024-06-20 06:50 UTC, jandroav approved these changes

2024-06-20 06:53 UTC, merged